"""add rule chat scope

Revision ID: 73e8a39284c7
Revises: 691059e6922a
Create Date: 2026-09-07 17:26:47.504245

"""
from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = '73e8a39284c7'
down_revision: str | Sequence[str] | None = '691059e6922a'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('rules', sa.Column('target_telegram_user_id', sa.BigInteger(), nullable=True))
    op.add_column('rules', sa.Column('target_label', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('rules', 'target_label')
    op.drop_column('rules', 'target_telegram_user_id')
    # ### end Alembic commands ###
